Added rds-aurora to terraform
USSBA/sba-gov-infrastructure pull request #490
Opened 2020-09-15 21:10 UTC by cdcampbell24

2020-09-15 21:24 UTC, bushong1 commented on terraform/application/modules/rds/rds-aurora.tf
> +    "Environment" = "mint"
Hardcoded

2020-09-16 15:12 UTC, jsmigovsky requested changes

2020-09-16 15:12 UTC, jsmigovsky commented on terraform/application/IMPORT_GUIDE.md
> +tf import 'module.rds.aws_route53_record.sbagov_db_record' "ZFA32P2PPHOAL_content-db.$(terraform workspace show).ussba.io_CNAME"
split this out for staging and production

2020-09-16 15:12 UTC, jsmigovsky commented on terraform/application/modules/rds/rds-aurora.tf
> +    local.all[terraform.workspace],
lets see if the `key` exists and only use it when it does

2020-09-16 15:12 UTC, jsmigovsky commented on terraform/application/modules/rds/rds-aurora.tf
> +  apply_immediately               = true
set to `false` or make variable depend on environment

2020-09-16 15:12 UTC, jsmigovsky commented on terraform/application/modules/rds/rds-aurora.tf
> +  engine_version                  = "5.6.10a"
make engine version a variable with a default of 5.6.10a

2020-09-16 15:12 UTC, jsmigovsky commented on terraform/application/modules/rds/rds-aurora.tf
> +  allowed_cidr_blocks             = ["10.20.0.0/20", "20.20.0.0/20"]
delete this, we are passing in a security group

2020-09-16 15:12 UTC, jsmigovsky commented on terraform/application/rds.tf
> +  vpc_id             = local.vpc_id
module.vpc.vpc_id

2020-09-16 15:12 UTC, jsmigovsky commented on terraform/application/rds.tf
> +  private_subnets    = local.private_subnets
module.vpc.priviate_subnets

2020-09-16 15:53 UTC, bushong1 approved these changes

2020-09-16 15:54 UTC, jsmigovsky approved these changes

2020-09-16 15:55 UTC, merged